#!/usr/bin/env node
/*
 * Concatenates the block stylesheets into one file per page type.
 *
 * The blocks stay as separate source files — the manifests in styles/ list
 * them in order, using the same @import syntax as before. This script resolves
 * those imports at build time and writes a single flat stylesheet to assets/.
 *
 * Why not just ship the manifests and let the browser follow the @imports:
 * a browser cannot discover an @import until the parent sheet has downloaded
 * and parsed, so every block arrives a round trip late. Listing them as
 * separate <link> tags avoids that waterfall but still costs one request each,
 * and the page paints unstyled until the last one lands. One file is one
 * request, and nothing renders before it.
 *
 * With --inline (what Netlify runs on deploy) it goes one step further and
 * embeds each bundle directly into the pages that use it, then drops the
 * stylesheet link. Firefox performs its initial paint after a few
 * milliseconds whether or not stylesheets have arrived, so *any* external
 * stylesheet — however fast, however well cached — can produce a visibly
 * unstyled frame. Inlining removes the request, so there is nothing to wait
 * for and nothing to flash. Fonts are self-hosted and preloaded, so a
 * deployed page has no render-blocking request left at all.
 *
 * The committed HTML keeps the <link>, so the repo stays readable and the
 * pages still work opened straight from disk. Only the deployed copy is
 * rewritten.
 *
 * Run with: npm run build:css           (write assets/ only)
 *           npm run build:css -- --inline   (also rewrite the HTML)
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "styles");
const OUT = path.join(ROOT, "assets");

const IMPORT = /@import\s+url\(\s*['"]?\.\.\/([^'")]+)['"]?\s*\)\s*;?/g;

function build(manifestPath) {
  const name = path.basename(manifestPath);
  const manifest = fs.readFileSync(manifestPath, "utf8");

  const files = [...manifest.matchAll(IMPORT)].map((m) => m[1]);
  if (files.length === 0) {
    throw new Error(`${name}: no @import rules found — is the manifest empty?`);
  }

  const parts = files.map((file) => {
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full)) {
      throw new Error(`${name}: imports ${file}, which does not exist`);
    }
    const css = fs.readFileSync(full, "utf8");
    if (IMPORT.test(css)) {
      IMPORT.lastIndex = 0;
      throw new Error(`${file}: nested @import — the build only resolves one level`);
    }
    return `/* ===== ${file} ===== */\n${css.trim()}\n`;
  });

  const banner =
    `/* Generated by scripts/build-css.js from styles/${name} — do not edit.\n` +
    ` * Edit the block files in blocks/ or the manifest in styles/ instead. */\n\n`;

  const out = banner + parts.join("\n");
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, name), out);

  return { name, blocks: files.length, bytes: out.length };
}

/* Embed the bundle into the pages that link it. */
function inlineInto(html) {
  const file = path.join(ROOT, html);
  let src = fs.readFileSync(file, "utf8");

  const link = src.match(
    /( *)<link rel="stylesheet" href="(?:\.\/|\/)assets\/([a-z-]+\.css)" \/>\n/
  );
  if (!link) return null;

  const [, indent, bundle] = link;
  const css = fs.readFileSync(path.join(OUT, bundle), "utf8");

  src = src.replace(
    link[0],
    `${indent}<style>\n${css.trimEnd()}\n${indent}</style>\n`
  );


  fs.writeFileSync(file, src);
  return { html, bundle, bytes: css.length };
}

const manifests = fs
  .readdirSync(SRC)
  .filter((f) => f.endsWith(".css"))
  .map((f) => path.join(SRC, f));

if (manifests.length === 0) {
  console.error("No manifests found in styles/");
  process.exit(1);
}

let failed = false;
for (const m of manifests) {
  try {
    const r = build(m);
    console.log(`assets/${r.name}  ${r.blocks} blocks, ${(r.bytes / 1024).toFixed(1)} KB`);
  } catch (err) {
    console.error(`ERROR ${err.message}`);
    failed = true;
  }
}

if (process.argv.includes("--inline")) {
  const pages = fs.readdirSync(ROOT).filter((f) => f.endsWith(".html"));
  let inlined = 0;
  for (const p of pages) {
    try {
      const r = inlineInto(p);
      if (r) {
        console.log(`${r.html}  inlined ${r.bundle} (${(r.bytes / 1024).toFixed(1)} KB)`);
        inlined++;
      }
    } catch (err) {
      console.error(`ERROR ${p}: ${err.message}`);
      failed = true;
    }
  }
  if (inlined === 0) {
    console.error("ERROR --inline matched no pages; the link markup may have changed");
    failed = true;
  }
}

process.exit(failed ? 1 : 0);
