#!/usr/bin/env node
/*
 * Concatenates the block stylesheets into one file per page type.
 *
 * The blocks stay as separate source files — the manifests in styles/ list
 * them in order, using the same @import syntax as before. This script resolves
 * those imports at build time and writes a single flat stylesheet to assets/.
 *
 * Why not just ship the manifests and let the browser follow the @imports:
 * a browser cannot discover an @import until the parent sheet has downloaded
 * and parsed, so every block arrives a round trip late. Listing them as
 * separate <link> tags avoids that waterfall but still costs one request each,
 * and the page paints unstyled until the last one lands. One file is one
 * request, and nothing renders before it.
 *
 * Run with: npm run build:css   (Netlify runs it automatically on deploy)
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "styles");
const OUT = path.join(ROOT, "assets");

const IMPORT = /@import\s+url\(\s*['"]?\.\.\/([^'")]+)['"]?\s*\)\s*;?/g;

function build(manifestPath) {
  const name = path.basename(manifestPath);
  const manifest = fs.readFileSync(manifestPath, "utf8");

  const files = [...manifest.matchAll(IMPORT)].map((m) => m[1]);
  if (files.length === 0) {
    throw new Error(`${name}: no @import rules found — is the manifest empty?`);
  }

  const parts = files.map((file) => {
    const full = path.join(ROOT, file);
    if (!fs.existsSync(full)) {
      throw new Error(`${name}: imports ${file}, which does not exist`);
    }
    const css = fs.readFileSync(full, "utf8");
    if (IMPORT.test(css)) {
      IMPORT.lastIndex = 0;
      throw new Error(`${file}: nested @import — the build only resolves one level`);
    }
    return `/* ===== ${file} ===== */\n${css.trim()}\n`;
  });

  const banner =
    `/* Generated by scripts/build-css.js from styles/${name} — do not edit.\n` +
    ` * Edit the block files in blocks/ or the manifest in styles/ instead. */\n\n`;

  const out = banner + parts.join("\n");
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, name), out);

  return { name, blocks: files.length, bytes: out.length };
}

const manifests = fs
  .readdirSync(SRC)
  .filter((f) => f.endsWith(".css"))
  .map((f) => path.join(SRC, f));

if (manifests.length === 0) {
  console.error("No manifests found in styles/");
  process.exit(1);
}

let failed = false;
for (const m of manifests) {
  try {
    const r = build(m);
    console.log(`assets/${r.name}  ${r.blocks} blocks, ${(r.bytes / 1024).toFixed(1)} KB`);
  } catch (err) {
    console.error(`ERROR ${err.message}`);
    failed = true;
  }
}
process.exit(failed ? 1 : 0);
